### ISSUE TITLE
Inexplicable "parsing error"

### ISSUE THREAD

**Issue by oletizi** [avinetworks/ansible-role-aviconfig#6]
Once I figured out how to specify the username and password, I got the error you'll see in the attached output file: [ansible.output.txt](https://github.com/avinetworks/ansible-role-aviconfig/files/1708786/ansible.output.txt)
.
It looks like a big json object is trying to be parsed as an URL somewhere in the Avi API.

Here is the task configuration:

<pre>
---
- name: Set ip facts
  set_fact:
    controller_public_ip: "{{ avi_controller.public_ip_address }}"
    docs_stage_private_ip: "{{ avi_docs_stage.private_ip_address }}"
  when: controller_public_ip is not defined

- debug: msg="controller_public_ip -- {{ controller_public_ip }}"
- debug: msg="docs_stage_private_ip -- {{ docs_stage_private_ip }}"
- debug: msg="avi_credentials_file -- {{ avi_credentials_file }}"

- name: Define Avi Controller configuration
  set_fact:
    avi_config:
      pool:
        - name: "docs-stage-pool"
          lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
          servers:
            - ip:
                 addr: "{{ docs_stage_private_ip }}"
                 type: 'V4'
      virtualservice:
        - name: "docs-stage"
          services:
            - port: 80
            - port: 443
          pool_ref: "/api/pool?name=docs-stage"
          vip:
            - ip_address:
                addr: "35.165.242.134"
                type: 'V4'
              vip_id: '1'
- name: Configure Avi Controller
  import_role:
    name: avinetworks.aviconfig
  vars:
    avi_config: "{{avi_config}}"
    avi_creds_file: "{{ avi_credentials_file }}"
</pre>

**Comment by ericsysmin** [comment]
@oletizi are you still getting that error?
